export class ConstantUI {

  static readonly SIZE_6 = 6
  static readonly SIZE_8 = 8
  static readonly SIZE_10 = 10
  static readonly SIZE_14 = 14
  static readonly SIZE_16 = 16
  static readonly SIZE_18 = 18
  static readonly SIZE_20 = 20
  static readonly SIZE_22 = 22
  static readonly SIZE_24 = 24
  static readonly SIZE_36 = 36
  static readonly SIZE_48 = 48
  static readonly SIZE_50 = 50
  static readonly CONST_0 = 0
  static readonly CONST_60 = 60

  static readonly FULL_WIDTH = '100%'
  static readonly FULL_HEIGHT = '100%'
  static readonly FULL_WIDTH_90 = '90%';
  static readonly FULL_HEIGHT_90 = '90%';
  static readonly BUTTON_WIDTH = '80%'
  static readonly BUTTON_WIDTH_HALF = '40%'

  static readonly BUTTON_RED = Color.Red
  static readonly BUTTON_GRAY = Color.Gray
  static readonly BUTTON_WHITE = Color.White
  static readonly BACKGROUND_BLACK = Color.Black
  static readonly TEXT_GRAY = '#666666'
  static readonly BUTTON_ORANGE = '#fe8627'
  static readonly TEXT_WHITE = '#ffffff'

  static readonly FONT_BOLD = FontWeight.Bold
  static readonly FONT_MEDIUM = FontWeight.Medium
  static readonly TEXT_ALIGN_CENTER = TextAlign.Center

  static readonly BUTTON_RADIUS = 10

  static readonly TEXT_PADDING = 8
  static readonly TEXT_PADDING_LARGE = 12
  static readonly PAGE_PADDING = 16
}
